'''
pipeline {
    agent any
    stages{
        stage('Build') {
            steps {
                echo "building the application"
                sh 'npm install'
            }
        }
        stage('test') {
            echo "Running test"
            sh 'npm test'
        }
    }
}
---

pipeline {
    agent any
    stages{
        stage('hello') {
            steps {
                echo "Hello Jenkins"
            }
        }
    }
}

---

pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                echo "checkout stage running"
            }
        }
        stage('Build') {
            steps {
                echo "Build ho raha hai"
            }
        }
        stage('Test') {
            steps {
                echo "Test ho raha hai"
            }
        }
    }
}
'''
'''
pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                echo "Checkout is running"
            }
        }
        stage('Build') {
            steps {
                echo "Build ho raha hai"
                sh 'ls -la'
            }
        }
        stage('Test') {
            steps {
                echo "Test ho raha hai"
                sh 'exit 1'
            }
        } 
    }
}
'''

'''
pipeline {
    agent any
    environment {
        APP_ENV = 'staging'
    }
    stages {
        stage ('Build') {
            steps {
                echo "$APP_ENV"
            }
        }
    }
}
'''
'''
pipeline {
    agent any
    environment {
    // environment hamesa agent any ke baad aur stages se pahale lkhte hai.
    // Environment variable ko hamesa '$' sign ke saath use karo jab print/use karna ho, 
    // '=' sign sirf define karte waqt use hota hai
        APP_ENV = 'staging'
    }
    stages {
        stage('Build') {
            steps {
                echo "build ho raha hai"
                echo "Current Environment is: ${APP_ENV}"
            }
        }
    }
    post {
        always {
           echo "Pipeline execution completed" 
        }
        success {
            echo "Build passed!"
        }
        failure {
            echo "Build failed, check logs"
        }
    }
}

pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                echo "Build ho raha hai"
            }
        }
        stage('deploy') {
        // ye if condition hai, Is stage ko tabhi chalao jab branch main ho, warna skip kardo
            when {
                branch 'main'
            }
            steps {
                echo "Deploying to production"
            }
        }
    }
}

pipeline {
    agent any
    options {
        timeout(time: 10, unit: 'MINUTES')
    }
    // kabhi kabhi build scripts kisi error, network issue, 
    // ya input prompt ki wajah se infinite loop me fass sakta hai.
    // agar timeout set nahi hoga, toh aapka jenkins agent ghanto tak busy rahega aur aapke resources(and cost) waste hote rahenge.
    stages {
        stage('build') {
            steps {
                echo "build ho raha hai"
            }
        }
        stage('deploy') {
            steps {
                echo "build complete hogaeya"
            }
        }
    }
}

pipeline {
    agent any
    
    parameters {
        // Name ko 'RUN_TESTS' kiya taaki niche use kiya ja sake
        booleanParam(name: 'RUN_TESTS', defaultValue: true, description: 'Do you want to run tests?')  
    }
    
    stages {
        stage('Test') {
            when {
                expression {
                    // Spelling thik ki: params.RUN_TESTS
                    params.RUN_TESTS == true
                }
            }
            steps {
                echo "This parameter check is done, running tests!"
            }
        }
    }
}


pipeline {
    agent any
    stages {
        stage('checkout') {
            // Yahan se 'when' block hata diya taaki checkout har branch pe ho
            steps {
                sh 'git status'
                echo "checkout from git"
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Run Test') {
            steps {
                echo "Run karo aur Test karo"
                sh 'npm test'
            }
        }
        stage('Build Docker Image') {
            steps {
                // 'myapp' aur '.' ke beech mein space add kiya
                sh 'sudo docker build -t myapp .'
            }
        }
        stage('Push to Registry') {
            steps {
                sh 'docker push myapp'
            }
        }
        stage('Deploy') {
            // Task ke mutabik 'when' block ko sahi jagah (Deploy stage mein) lagaya
            when {
                branch 'main'
            }
            steps {
                sh './deploy.sh'
                echo "Deploy successfully"
            }
        }
    }
}


pipeline {
    agent any
    environment {
        DOCKER_CREDS = credentials('docker-hub-creds')
    }
    stages {
        stage('docker login') {
            steps{
                sh "echo \"\$DOCKER_CREDS_PSW\" | docker login -u \"\$DOCKER_CREDS_USR\" --password-stdin"
            }
        }
    }
}

pipeline {
    agent none
    
    stages {
        stage('Checkout') {
            agent any
            
            steps {
                echo "Checking out code on an available agent..."
            }
        }
        
        stage('Build and Test') {
            agent {
                label 'linux-heavy-node'
            }
            steps {
                echo "Running heavy build on Linux node..."
            }
        }
    }
}
'''

pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "Build the application"
            }
        }
        stage('unit Test and lint check') {
            parallel {
                stage('Unit Tests') {
                    steps {
                        echo "Unit tests is done"
                    }
                }
                stage('Lint check') {
                    steps {
                        echo "Lint check is done"
                    }
                }
            }
        }
    }
}