'''
pipeline {
    agent any
    stages{
        stage('Build') {
            steps {
                echo "building the application"
                sh 'npm install'
            }
        }
        stage('test') {
            echo "Running test"
            sh 'npm test'
        }
    }
}
---

pipeline {
    agent any
    stages{
        stage('hello') {
            steps {
                echo "Hello Jenkins"
            }
        }
    }
}

---

pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                echo "checkout stage running"
            }
        }
        stage('Build') {
            steps {
                echo "Build ho raha hai"
            }
        }
        stage('Test') {
            steps {
                echo "Test ho raha hai"
            }
        }
    }
}
'''

